apiVersion: apps/v1
kind: Deployment
metadata:
  name: insuranceportal-deploy
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:           
      containers:
      - name: insuranceclient
        image: ashashivdasani/insuranceclient:latest        
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        